repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.7
    hooks:
      - id: ruff
        name: Ruff (lint + auto-fix)
        args: ["--fix", "--exit-zero"] 
        pass_filenames: true
        always_run: true

      - id: ruff-format
        name: Ruff (format)
        pass_filenames: true
        always_run: true
